### ISSUE TITLE
Can't install autolabel successfully using 'pip3 install whl-autolabel' command

### ISSUE THREAD

**Issue by huan0808** [wheelos/autolabel#6]
Hi, after I run installation command, it says no matching distribution. I could install other packages using pip so my network is good and my pip source is default.
![image](https://github.com/user-attachments/assets/f7e79f50-de18-45c2-801e-325a4d8c5a5c)

**Comment by daohu527** [comment]
I fixed the installation issue and am currently debugging it. Please report any issues.

My current environment is codespace, and I will use Google Colab next, so that you can run it.

**Comment by daohu527** [comment]
@huan0808 fixed cc6248cf6d5b9103e60027a3fc5c81d918ca4aa6
